import type { PhotoSource } from './photoSources';
import photo0 from '../../assets/spotlog/licensed-places/hyeopjae-scenery.jpg';
import photo1 from '../../assets/spotlog/licensed-places/hyeopjae-shore.jpg';
import photo2 from '../../assets/spotlog/licensed-places/osulloc-museum.jpg';
import photo3 from '../../assets/spotlog/licensed-places/osulloc-tea.jpg';
import photo4 from '../../assets/spotlog/licensed-places/sagye-coast.jpg';
import photo5 from '../../assets/spotlog/licensed-places/sagye-rocks.jpg';
import photo6 from '../../assets/spotlog/licensed-places/saebyeol-autumn.jpg';
import photo7 from '../../assets/spotlog/licensed-places/saebyeol-ridge.jpg';
import photo8 from '../../assets/spotlog/licensed-places/seoulforest-path.jpg';
import photo9 from '../../assets/spotlog/licensed-places/anmok-beach.jpg';

/** Actual place photos; original attribution and licenses are per asset. */
export const licensedPlaceSources: PhotoSource[] = [
  { ...{
  "id": "commons-hyeopjae-scenery",
  "placeId": "jeju-hyeopjae",
  "title": "협재해수욕장 · 비양도와 백사장",
  "originalTitle": "Hyeopjae Beach Scenery.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hyeopjae_Beach_Scenery.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Hyeopjae_Beach_Scenery.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "Lcarrion88",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2014-03-03 13:58:42",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "파도 너머 비양도를 바라보는 협재해변.",
  "objectPosition": "70% 50%"
}, image: photo0 },
  { ...{
  "id": "commons-hyeopjae-shore",
  "placeId": "jeju-hyeopjae",
  "title": "협재해수욕장 · 현무암 해안",
  "originalTitle": "Hyeopjae.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hyeopjae.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Hyeopjae.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "Lcarrion88",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2014-03-03 13:52:20",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "검은 현무암과 푸른 바다가 맞닿은 협재해변.",
  "objectPosition": "50% 50%"
}, image: photo1 },
  { ...{
  "id": "commons-osulloc-museum",
  "placeId": "jeju-osulloc",
  "title": "오설록 티뮤지엄 · 건물 전경",
  "originalTitle": "O'Sulloc Tea Museum, Jeju (오설록 녹차박물관, 제주) - panoramio.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:O%27Sulloc_Tea_Museum,_Jeju_(%EC%98%A4%EC%84%A4%EB%A1%9D_%EB%85%B9%EC%B0%A8%EB%B0%95%EB%AC%BC%EA%B4%80,_%EC%A0%9C%EC%A3%BC)_-_panoramio.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/e/ed/O%27Sulloc_Tea_Museum%2C_Jeju_%28%EC%98%A4%EC%84%A4%EB%A1%9D_%EB%85%B9%EC%B0%A8%EB%B0%95%EB%AC%BC%EA%B4%80%2C_%EC%A0%9C%EC%A3%BC%29_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "골뱅이 (IM Seongbin)",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2010-12-12 (원본 최초 업로드일 · 촬영일 미상)",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "오설록 티뮤지엄의 과거 전경. 현재 시설 모습은 다를 수 있어요.",
  "objectPosition": "55% 50%"
}, image: photo2 },
  { ...{
  "id": "commons-osulloc-tea",
  "placeId": "jeju-osulloc",
  "title": "오설록 티뮤지엄 · 차나무",
  "originalTitle": "Camellia Sinensis, O'Sulloc Tea Museum, Jeju (차나무, 오설록 녹차박물관, 제주) - panoramio.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Camellia_Sinensis,_O%27Sulloc_Tea_Museum,_Jeju_(%EC%B0%A8%EB%82%98%EB%AC%B4,_%EC%98%A4%EC%84%A4%EB%A1%9D_%EB%85%B9%EC%B0%A8%EB%B0%95%EB%AC%BC%EA%B4%80,_%EC%A0%9C%EC%A3%BC)_-_panoramio.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Camellia_Sinensis%2C_O%27Sulloc_Tea_Museum%2C_Jeju_%28%EC%B0%A8%EB%82%98%EB%AC%B4%2C_%EC%98%A4%EC%84%A4%EB%A1%9D_%EB%85%B9%EC%B0%A8%EB%B0%95%EB%AC%BC%EA%B4%80%2C_%EC%A0%9C%EC%A3%BC%29_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "골뱅이 (IM Seongbin)",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2010-12-12 (원본 최초 업로드일 · 촬영일 미상)",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "오설록에서 가까이 바라본 차나무와 찻잎.",
  "objectPosition": "50% 50%"
}, image: photo3 },
  { ...{
  "id": "commons-sagye-coast",
  "placeId": "jeju-sagye",
  "title": "사계해안 · 산방산과 해변",
  "originalTitle": "Sagye Beach 01.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sagye_Beach_01.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/5/56/Sagye_Beach_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "Grapesurgeon",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2026-05-05 17:06:53",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "사계해변 너머로 보이는 산방산과 해안 풍경.",
  "objectPosition": "33% 50%"
}, image: photo4 },
  { ...{
  "id": "commons-sagye-rocks",
  "placeId": "jeju-sagye",
  "title": "사계해안 · 바위와 바다",
  "originalTitle": "Sagye Beach 03.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sagye_Beach_03.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Sagye_Beach_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "Grapesurgeon",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2026-05-05 16:49:53",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "사계의 바위 해안에서 바라본 바다.",
  "objectPosition": "50% 50%"
}, image: photo5 },
  { ...{
  "id": "commons-saebyeol-autumn",
  "placeId": "jeju-saebyeol",
  "title": "새별오름 · 가을 억새와 노을",
  "originalTitle": "새별오름.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:%EC%83%88%EB%B3%84%EC%98%A4%EB%A6%84.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8b/%EC%83%88%EB%B3%84%EC%98%A4%EB%A6%84.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "HiHoHo",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2016-10-19 17:37:56",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "억새 사이로 이어지는 새별오름의 가을 산책길.",
  "objectPosition": "50% 50%"
}, image: photo6 },
  { ...{
  "id": "commons-saebyeol-ridge",
  "placeId": "jeju-saebyeol",
  "title": "새별오름 · 봄 전경",
  "originalTitle": "Saebyeol Oreum 01.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Saebyeol_Oreum_01.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Saebyeol_Oreum_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "Grapesurgeon",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2026-05-01 12:37:02",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "잔디 너머로 바라본 새별오름의 봄 능선.",
  "objectPosition": "43% 50%"
}, image: photo7 },
  { ...{
  "id": "commons-seoulforest-path",
  "placeId": "seoul-seoulforest",
  "title": "서울숲 · 가을 산책길",
  "originalTitle": "Seoulforest path01.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Seoulforest_path01.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Seoulforest_path01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "Enigma7seven",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2009-11-26",
  "changes": "원본 파일 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "낙엽이 내려앉은 서울숲의 산책길.",
  "objectPosition": "50% 50%"
}, image: photo8 },
  { ...{
  "id": "commons-anmok-beach",
  "placeId": "gangneung-anmok",
  "title": "안목해변 · 해변 전망대",
  "originalTitle": "Anmok Beach 20220430 001.jpg",
  "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anmok_Beach_20220430_001.jpg",
  "imageSourceUrl": "https://upload.wikimedia.org/wikipedia/commons/7/71/Anmok_Beach_20220430_001.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "owner": "Wikimedia Commons",
  "author": "Mobius6",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "verifiedAt": "2026-09-15",
  "publishedAt": "2022-04-30 16:16:01",
  "changes": "Wikimedia Commons 제공 축소본 사용. 파일 추가 편집 없음. 화면 비율에 따라 일부가 잘려 보일 수 있습니다.",
  "reuseNote": "저작자와 출처·이용허락 링크를 표시해야 합니다. 사진을 수정하여 공유할 때에는 동일한 이용허락 조건을 따라야 합니다.",
  "caption": "바다를 바라보는 안목해변의 전망대.",
  "objectPosition": "50% 50%"
}, image: photo9 }
];
