import { Ionicons } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useSpotlog } from '../context/SpotlogContext';
import { colors, radius, shadow } from '../theme';

export function TripsScreen() {
  const { draft } = useSpotlog();
  return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.header}><Text style={styles.eyebrow}>MY JOURNEYS</Text><Text style={styles.title}>내 여행</Text><Text style={styles.copy}>준비 중인 일정과 여행 중 가이드, 다녀온 기록을 한곳에서 관리합니다.</Text></View>{draft ? <View style={styles.card}><View style={styles.cardTop}><View style={styles.icon}><Ionicons name="map" size={23} color={colors.primary} /></View><View style={styles.cardCopy}><Text style={styles.status}>작성 중 · {draft.nights}박 {draft.days}일</Text><Text style={styles.cardTitle}>{draft.title}</Text><Text style={styles.meta}>{draft.startDate} – {draft.endDate} · {draft.items.length}개 장소</Text></View></View><View style={styles.progress}><View style={styles.progressFill} /></View><Text style={styles.progressText}>일정 초안 60% 완성</Text><View style={styles.actions}><Pressable style={styles.secondary}><Text style={styles.secondaryText}>공유 미리보기</Text></Pressable><Pressable style={styles.primary}><Text style={styles.primaryText}>계속 편집</Text></Pressable></View></View> : <View style={styles.empty}><Ionicons name="trail-sign-outline" size={40} color={colors.muted} /><Text style={styles.emptyTitle}>첫 여행을 만들어보세요</Text><Text style={styles.emptyCopy}>발견에서 장면을 담으면 나만의 일정으로 이어집니다.</Text></View>}</SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, header: { padding: 20 }, eyebrow: { color: colors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, title: { color: colors.ink, fontSize: 30, fontWeight: '900', marginTop: 5 }, copy: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 7 }, card: { margin: 20, marginTop: 6, padding: 18, borderRadius: radius.lg, backgroundColor: '#fff', ...shadow }, cardTop: { flexDirection: 'row', gap: 13 }, icon: { width: 52, height: 52, borderRadius: 18, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, cardCopy: { flex: 1 }, status: { color: colors.primary, fontSize: 10, fontWeight: '900' }, cardTitle: { color: colors.ink, fontSize: 19, fontWeight: '900', marginTop: 4 }, meta: { color: colors.muted, fontSize: 11, marginTop: 5 }, progress: { height: 7, borderRadius: 4, backgroundColor: colors.line, marginTop: 20, overflow: 'hidden' }, progressFill: { width: '60%', height: '100%', backgroundColor: colors.accent }, progressText: { color: colors.muted, fontSize: 10, marginTop: 6 }, actions: { flexDirection: 'row', gap: 8, marginTop: 18 }, secondary: { flex: 1, height: 45, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: colors.ink, fontWeight: '800', fontSize: 12 }, primary: { flex: 1, height: 45, borderRadius: radius.sm, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: '#fff', fontWeight: '900', fontSize: 12 }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30 }, emptyTitle: { color: colors.ink, fontSize: 20, fontWeight: '900', marginTop: 12 }, emptyCopy: { color: colors.muted, textAlign: 'center', marginTop: 6 } });
