'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowUpRight,ArrowLeft,Check,ChevronRight,Clock3,CloudRain,Coffee,Copy,History,Layers3,MapPin,Navigation,Plane,RotateCcw,ShoppingBag,Sparkles,Ticket,Utensils,Wallet,Languages,Info,Car,Route,BookOpen,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {catalog,examples,followups,initialState,unitDiff,type Snapshot,type Unit} from '@/lib/unit-engine';
const icons={time:Clock3,route:Route,food:Utensils,pickup:ShoppingBag,budget:Wallet,indoor:CloudRain,rest:Coffee,translation:Languages,booking:Ticket,faq:BookOpen,plan:Navigation,transport:Car};
const money=(v:number)=>v.toLocaleString('ko-KR')+'원';
const foods=[{name:'따뜻한 우동',description:'순한 맛 · 앉아서 식사',price:9000,wait:12},{name:'샌드위치 & 주스',description:'들고 가기 좋은 한 끼',price:8500,wait:8}];
type Session={current:Snapshot;history:Snapshot[]};
type Panel='units'|'history'|'about'|'photo'|'booking'|'faq'|null;
type Context={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options?:{signal:AbortSignal})=>unknown};
function Composition({s,previous}:{s:Snapshot;previous?:Snapshot}){const diff=unitDiff(previous,s);return <div className="composition"><span className="overline">LIVE COMPOSITION</span><h2>{catalog.length}개 중 {s.units.length}개가<br/>지금 필요해요.</h2><p>대화와 조건을 함께 보고 필요한 유닛의 순서와 표현을 바꿔요.</p><div className="assembly-list">{s.units.map((u,i)=>{const Icon=icons[u.id];return <div className="assembly-item" key={u.id}><span>{String(i+1).padStart(2,'0')}</span><Icon size={17}/><div><strong>{u.title}</strong><small>{u.reason}</small></div><b>{u.variant==='lead'?'먼저':u.variant==='compact'?'요약':'상세'}</b></div>;})}</div>{previous&&<div className="delta-detail"><h3>이번 말로 바뀐 것</h3>{diff.added.map(u=><p key={u.id}><span className="coral">+ 추가</span>{u.title}</p>)}{diff.removed.map(u=><p key={u.id}><span>− 제외</span>{u.title}</p>)}{diff.changed.map(u=><p key={u.id}><span>↗ 재구성</span>{u.title}</p>)}</div>}<div className="unit-pool"><h3>필요할 때 꺼내는 유닛</h3>{catalog.filter(u=>!s.units.some(x=>x.id===u.id)).map(u=><span key={u.id}>{u.title}</span>)}</div><p className="technical-note">{s.mode==='jev'?`Jev 판단 · ${s.model} · 실제 호출 ${s.elapsedMs}ms`:'현재는 규칙 기반 체험입니다. Jev API는 연결 준비 상태이며 실제 성능은 아직 검증하지 않았습니다.'}</p></div>;}
export default function TravelWorkspace(){
 const [session,setSession]=useState<Session>({current:initialState,history:[]});const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [panel,setPanel]=useState<Panel>(null);const [textOnly,setTextOnly]=useState(false);const [food,setFood]=useState(0);const [selected,setSelected]=useState(false);const [copied,setCopied]=useState(false);
 const live=useRef(session);live.current=session;const sequence=useRef(0);const anchor=useRef<HTMLDivElement>(null);
 const s=session.current,f=s.facts,previous=session.history.at(-1),diff=unitDiff(previous,s);const meal=foods[f.takeaway?1:food];const mealCost=f.food?meal.price*(f.child?2:1):0,transportCost=f.transport?6500:0,restCost=f.rest?5000:0,total=mealCost+transportCost+restCost;
 const travelMinutes=f.mobility||f.transport?6:12,mealMinutes=f.food?(f.takeaway?meal.wait:28):0,freeTime=(f.minutes??0)-travelMinutes-mealMinutes-10;
 const faqTitle=f.faqTopic==='luggage'?'짐은 먼저 맡길 수 있나요?':f.faqTopic==='cancel'?'예약 취소는 어떻게 하나요?':'해당 규정은 확인이 필요해요.';
 const faqText=f.faqTopic==='luggage'?'체험용 숙소 규정에서는 체크인 당일 프런트에 보관을 요청할 수 있어요. 귀중품은 직접 보관해 주세요.':f.faqTopic==='cancel'?'체험용 취소 안내에서는 예약 확인서의 취소 가능 기한과 수수료 조건을 먼저 확인하도록 안내해요. 실제 예약 조건은 조회하지 않았어요.':'이 체험 자료에는 짐 보관과 예약 취소 안내만 있어요. 질문에 맞는 실제 규정을 조회할 연결이 필요해요.';
 const phrase=f.takeaway?'Could I get this to go, please?':f.faq?'Could you store our luggage until check-in?':f.food?'Do you have a mild dish for a child?':'Is there somewhere quiet where we can rest?';
 const phraseKo=f.takeaway?'이거 포장해 주실 수 있나요?':f.faq?'체크인까지 짐을 맡길 수 있을까요?':f.food?'아이가 먹을 만한 맵지 않은 음식이 있나요?':'조용히 쉴 수 있는 곳이 있나요?';
 const say=useCallback(async(message:string,reset=false)=>{const question=message.trim();if(!question||question.length>500)return;const token=++sequence.current,old=live.current;setBusy(true);setError('');setInput('');try{const response=await fetch('/api/compose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,previous:reset?undefined:old.current,conversation:reset?[]:[...old.history,old.current].map(x=>x.question)}),signal:AbortSignal.timeout(16000)});const result=await response.json() as Snapshot & {error?:string};if(!response.ok)throw new Error(result.error??'요청을 처리하지 못했어요.');if(token!==sequence.current)return;setSession({current:result,history:reset?[]:[...old.history,old.current].slice(-20)});if(reset){setFood(0);setSelected(false);setTextOnly(false);}setCopied(false);anchor.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}catch(e){if(token===sequence.current){setError(e instanceof Error&&e.message.includes('Jev')?e.message:'연결이 잠시 끊겼어요. 다시 보내 주세요.');setInput(question);}}finally{if(token===sequence.current)setBusy(false);}},[]);
 const action=(q:string)=>{setPanel(null);void say(q);};
 const back=()=>{const history=[...session.history],last=history.pop();if(last){++sequence.current;setBusy(false);setError('');setSession({current:last,history});}};
 useEffect(()=>{const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const register=(tool:Parameters<Context['registerTool']>[0])=>{try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}};register({name:'read_demo_state',title:'Read composed travel workspace',description:'Read active units, carried context and whether Jev was actually used.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>live.current});register({name:'send_demo_message',title:'Change travel context',description:'Send a message through the visible demo. May call Jev if configured. No real purchases or reservations.',inputSchema:{type:'object',properties:{message:{type:'string',minLength:1,maxLength:500}},required:['message'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const message=(input as {message?:unknown}).message;if(typeof message!=='string'||!message.trim()||message.length>500)throw new Error('Invalid message');await say(message);return {submitted:message};}});return()=>controller.abort();},[say]);
 const renderUnit=(u:Unit)=>{const Icon=icons[u.id],compact=u.variant==='compact';return <section key={u.id} className={`travel-unit unit-${u.id} ${u.variant}`} data-unit={u.id} data-variant={u.variant} aria-label={u.title}><div className="unit-heading"><span className={'category '+u.id}><Icon size={14}/>{u.title}</span><span>{u.variant==='lead'?'지금 먼저':compact?'간단히':''}</span></div>
 {u.id==='time'&&<><div className="time-main"><div><span>{f.location==='airport'?'탑승까지':'약속한 시간까지'}</span><strong>{f.minutes}<small>분</small></strong></div><div className="time-plan"><p>이동 {travelMinutes}분{f.food?` + ${f.takeaway?'픽업':'식사'} ${mealMinutes}분`:''}</p><p>준비 여유 10분 포함</p><b className={freeTime<0?'warning-text':''}>{freeTime>=0?`${freeTime}분 여유`:`${Math.abs(freeTime)}분 부족`}</b></div></div><div className="time-track"><span style={{width:`${Math.min(100,(travelMinutes+mealMinutes+10)/Math.max(1,f.minutes??1)*100)}%`}}/></div>{freeTime<0&&<p className="notice">{f.food?'현재 조합은 시간 안에 어려워요. 식사를 빼거나 바로 이동하는 편을 확인하세요.':'먼저 이동하고, 휴식은 도착 후 남는 시간을 확인해요.'}</p>}</>}
 {u.id==='food'&&<><h2>{f.takeaway?'들고 갈 메뉴만 골랐어요.':f.child?'아이와 먹기 좋은 한 끼':'지금 가까운 한 끼'}</h2><div>{(compact?[meal]:f.takeaway?[foods[1]]:foods).map((item,i)=><button key={item.name} className={'place-row '+(selected&&item.name===meal.name?'chosen':'')} onClick={()=>{setFood(foods.indexOf(item));setSelected(true);}} aria-pressed={selected&&item.name===meal.name}><span className="place-icon food-icon"><Utensils size={24}/></span><span className="place-copy"><strong>{item.name}</strong><span>{item.description}</span><b>{money(item.price)} · 준비 {item.wait}분</b></span>{selected&&item.name===meal.name?<Check size={18}/>:<ChevronRight size={17}/>}</button>)}</div>{!compact&&<Button variant="outline" className="unit-action" onClick={()=>action(f.takeaway?'앉아서 먹을래':'포장해서 갈래')}>{f.takeaway?'앉아서 먹는 메뉴 보기':'포장해서 동선에 넣기'}<ArrowUpRight/></Button>}{selected&&<p className="selection-note"><Check size={13}/>{meal.name} 선택을 예산과 동선에 반영했어요.</p>}</>}
 {u.id==='pickup'&&<><h2>먹는 시간을, 이동 시간으로.</h2><div className="pickup-ticket"><ShoppingBag size={28}/><div><strong>{meal.name}</strong><span>준비 {meal.wait}분 · 가상 픽업 지점 A</span></div></div><div className="inline-steps"><span>메뉴 선택</span><ChevronRight size={14}/><span>준비 {meal.wait}분</span><ChevronRight size={14}/><span>동선에서 수령</span></div><Button className="unit-action" onClick={()=>{setSelected(true);action('픽업 지점을 넣은 동선 보여줘');}}>픽업 동선 보기<ArrowUpRight/></Button></>}
 {u.id==='route'&&<><h2>{f.mobility?'걷는 구간을 줄였어요.':f.takeaway?'들러서 받고, 바로 출발.':'필요한 곳만 연결했어요.'}</h2><ol className={'route-list '+(compact?'route-compact':'')}><li><i/><div><strong>현재 위치</strong><span>{f.location==='airport'?'출국장':f.location==='jeju'?'제주 여행 중':'호텔 근처'} · 가상 위치</span></div></li>{f.food&&<li><i/><div><strong>{f.takeaway?'포장 수령':'식사'} · {meal.name}</strong><span>이동 경로 안에서 들르기 · 준비 {meal.wait}분</span></div></li>}{f.rest&&<li><i/><div><strong>조용한 휴식 공간</strong><span>{f.child?'아이와 앉을 수 있는 곳':'잠깐 머물기'}</span></div></li>}<li><i/><div><strong>{f.location==='airport'?'탑승 게이트':f.booking?'체크인 장소':f.rain?'실내 장소':'다음 목적지'}</strong><span>{f.transport?'택시':f.mobility?'짧은 도보':'도보'} 경로 예시 · 이동 {travelMinutes}분</span></div></li></ol><p className="data-footnote">실제 위치를 조회하지 않은 동선 예시</p></>}
 {u.id==='budget'&&<><div className="budget-head"><div><span>예상 합계</span><strong>{money(total)}</strong></div><div><span>내 예산</span><b>{money(f.budget??0)}</b></div></div>{!compact&&<div className="cost-lines">{f.food&&<p><span>식사 · {f.child?'2인':'1인'}</span><b>{money(mealCost)}</b></p>}{f.rest&&<p><span>휴식 · 음료 예시</span><b>{money(restCost)}</b></p>}{f.transport&&<p><span>택시 · 예상</span><b>{money(transportCost)}</b></p>}</div>}<p className={'budget-balance '+(total>(f.budget??0)?'warning-text':'')}>{total>(f.budget??0)?`예산보다 ${money(total-(f.budget??0))} 많아요`:`${money((f.budget??0)-total)} 남아요`}</p></>}
 {u.id==='indoor'&&<>{f.location==='jeju'&&<div className="destination-image"><img src="/images/osulloc-museum.jpg" alt="제주 오설록 티뮤지엄의 과거 건물 전경"/><button onClick={()=>setPanel('photo')} aria-label="사진 출처 보기"><Info size={14}/></button></div>}<h2>{f.location==='jeju'?'비를 피하는 제주.':'비를 피할 실내 장소.'}</h2><p className="unit-description">실내 전시를 보고, 가까운 곳에서 {f.food?'식사와 ':''}{f.rest?'휴식까지 이어가요.':'다음 시간을 보내요.'}</p><div className="place-line"><MapPin size={15}/><strong>{f.location==='jeju'?'오설록 티뮤지엄':'가까운 실내 전시 공간'}</strong><span>장소 예시</span></div><Button variant="outline" className="unit-action" onClick={()=>action('식사와 휴식을 넣어 오늘의 순서 보여줘')}>오늘의 순서로 엮기<ArrowUpRight/></Button></>}
 {u.id==='rest'&&<><h2>{f.child?'잠깐, 아이 속도에 맞춰요.':'여기서 잠깐 쉬어가요.'}</h2><div className="place-row static"><span className="place-icon cafe-icon"><Coffee size={26}/></span><span className="place-copy"><strong>{f.location==='airport'?'게이트 근처 휴식 공간':'가까운 조용한 라운지'}</strong><span>{f.child?'유모차 옆 좌석 · 낮은 이동 부담':'앉아서 기다릴 수 있는 곳'}</span><b>{f.minutes!==null?(freeTime>0?`${freeTime}분 안에서 휴식`:'도착 후 여유가 생기면 휴식'):'30분 쉬어가기'} · 가상 예시</b></span></div>{!compact&&<Button variant="outline" className="unit-action" onClick={()=>action(f.location==='airport'?'동선만 보여줘':'걷기 힘드니까 택시로 갈래')}>{f.location==='airport'?'게이트 동선 먼저 보기':'걷는 구간 줄이기'}<ArrowUpRight/></Button>}</>}
 {u.id==='translation'&&<><p className="translation-ko">{phraseKo}</p><p className="translation-en" lang="en">{phrase}</p><Button variant="outline" className="unit-action" onClick={async()=>{try{await navigator.clipboard.writeText(phrase);setCopied(true);}catch{setError('문장을 길게 눌러 복사해 주세요.');}}}>{copied?'복사했어요':'문장 복사'}{copied?<Check/>:<Copy/>}</Button></>}
 {u.id==='booking'&&<><h2>체크인 정보, 한눈에.</h2><div className="booking-line"><Ticket size={28}/><div><strong>모아 스테이 · 예약 예시</strong><span>오늘 체크인 · 1박 · 2인</span></div></div><p className="booking-code">DEMO–2048 <span>가상 예약번호</span></p><Button variant="outline" className="unit-action" onClick={()=>setPanel('booking')}>예약 내용 확인<ChevronRight/></Button></>}
 {u.id==='faq'&&<><h2>{faqTitle}</h2><p className="unit-description">{faqText}</p><button className="source-link" onClick={()=>setPanel('faq')}><BookOpen size={14}/>근거: 체험용 숙소 FAQ<ChevronRight size={14}/></button></>}
 {u.id==='plan'&&<><h2>지금 상황으로 엮은 순서.</h2><div className="plan-items">{[f.food?`${f.takeaway?'포장 수령':'식사'} · ${meal.name}`:null,f.rest?'휴식 · 조용한 라운지':null,f.rain?'실내 · 전시 둘러보기':null,f.booking?'체크인 · 모아 스테이':null,f.location==='airport'?'이동 · 탑승 게이트':null].filter(Boolean).map((v,i)=><div key={v}><span>{String(i+1).padStart(2,'0')}</span><strong>{v}</strong></div>)}</div></>}
 {u.id==='transport'&&<><h2>시간과 걸음 수를 함께 봐요.</h2><div className="transport-options"><button onClick={()=>action('택시로 가는 동선 보여줘')}><Car size={23}/><strong>택시</strong><span>6분 · 도보 적음</span><b>6,500원 예시</b></button><button onClick={()=>action('택시는 필요 없어. 걸어도 돼. 동선 보여줘')}><Navigation size={23}/><strong>도보</strong><span>12분 · 직접 이동</span><b>0원</b></button></div></>}
 </section>;};
 return <div className="demo-stage"><div className="mobile-shell"><header className="topbar"><a href="/" className="brand">moa<span>여행</span></a><div className="top-actions"><button className="mode-badge" onClick={()=>setPanel('about')}>{s.mode==='jev'?'Jev 연결':'체험 모드'}<Info size={13}/></button><Button variant="ghost" size="icon" aria-label="처음부터" disabled={busy} onClick={()=>void say(examples[0].question,true)}><RotateCcw size={18}/></Button></div></header><main className="mobile-page"><div className="page-title"><span className="overline">YOUR TRAVEL, IN THE MOMENT</span><h1>지금, 필요한 것부터.</h1><p>상황이 달라지면 화면도 함께 바뀌어요.</p></div><div className="example-chips" aria-label="새 상황으로 시작">{examples.map(x=><Button key={x.label} variant="outline" disabled={busy} onClick={()=>void say(x.question,true)}>{x.label==='비 오는 제주'?<CloudRain/>:x.label==='탑승 전 70분'?<Plane/>:<Ticket/>}{x.label}</Button>)}</div>
 <div className="request-anchor" ref={anchor}><div className="request-meta"><span>나의 지금</span><div><Button variant="ghost" aria-label="이전 대화로" size="icon" onClick={back} disabled={!session.history.length||busy}><ArrowLeft/></Button><Button variant="ghost" onClick={()=>setPanel('history')}><History/>대화 {session.history.length+1}</Button></div></div><p className="request-text">{s.question}</p><div className="context-chips">{f.child&&<span>아이 동반</span>}{f.rain&&<span>실내 우선</span>}{f.takeaway&&<span>포장</span>}{f.mobility&&<span>도보 최소</span>}{f.budget&&<span>{money(f.budget)} 이내</span>}{f.minutes!==null&&<span>{f.minutes}분 남음</span>}</div></div><div className="composition-bar"><span><Sparkles size={15}/>{s.units.length}개 유닛으로 구성</span><button onClick={()=>setPanel('units')}>구성 보기<ChevronRight size={15}/></button></div>
 {previous&&<div className="change-strip" aria-live="polite">{diff.added.length>0&&<span>+ {diff.added.map(u=>u.title).join(' · ')}</span>}{diff.removed.length>0&&<span>− {diff.removed.map(u=>u.title).join(' · ')}</span>}{diff.changed.length>0&&<span>↗ {diff.changed.length}개 재배치·표현 변경</span>}{!diff.added.length&&!diff.removed.length&&!diff.changed.length&&<span>현재 구성을 유지하며 조건을 반영했어요.</span>}</div>}{(error||s.notice)&&<p className="notice error" role="status">{error||s.notice}</p>}
 <div className={'unit-stack '+(busy?'loading':'')} aria-busy={busy}>{textOnly?<section className="travel-unit text-summary"><h2>지금 필요한 정보</h2>{s.units.map(u=><p key={u.id}><strong>{u.title}</strong>{u.reason}</p>)}<Button variant="outline" onClick={()=>setTextOnly(false)}>유닛 화면으로 돌아가기</Button></section>:s.units.map(renderUnit)}{!s.units.length&&<section className="travel-unit"><h2>어떤 도움이 필요하세요?</h2><p>식사, 휴식, 이동처럼 지금 필요한 일을 말해 주세요.</p></section>}</div><div className="next-conversation"><span className="overline">상황을 더해 보세요</span><div>{followups(s).map(q=><Button disabled={busy} variant="outline" key={q} onClick={()=>void say(q)}>{q}<ArrowUpRight size={15}/></Button>)}</div></div><p className="sample-disclosure">장소·시간·요금·예약 정보는 체험용입니다.<br/>실제 위치 조회, 주문 또는 예약은 실행되지 않습니다.</p></main>
 <footer className="composer-dock"><form className="composer" onSubmit={e=>{e.preventDefault();void say(input);}}><input aria-label="여행 상황 입력" placeholder="상황이 바뀌었나요? 편하게 말해요" value={input} maxLength={500} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&e.nativeEvent.isComposing)e.preventDefault();}}/><Button type="submit" aria-label="상황 보내기" disabled={!input.trim()||busy}>{busy?<span>···</span>:<ArrowUp size={22}/>}</Button></form><div className="dock-caption"><span>{busy?'필요한 유닛을 구성하고 있어요…':s.mode==='jev'?'Jev가 대화를 판단했어요':'규칙 기반 체험 · Jev 미연동'}</span><button onClick={()=>setTextOnly(v=>!v)}>{textOnly?'화면으로':'글로 보기'}</button></div></footer></div>
 <aside className="desktop-inspector"><div className="inspector-header"><Layers3 size={20}/><strong>화면이 만들어지는 방식</strong></div><Composition s={s} previous={previous}/><button className="source-link" onClick={()=>setPanel('about')}>Jev 연결 상태와 체험 범위<ArrowUpRight size={15}/></button></aside>
 <Dialog open={panel!==null} onOpenChange={open=>{if(!open)setPanel(null);}}><DialogContent className="bottom-sheet" showCloseButton={false}><DialogHeader><div className="sheet-title-row"><DialogTitle>{panel==='units'?'지금의 화면 구성':panel==='history'?'대화가 바꾼 화면':panel==='photo'?'사진 출처':panel==='booking'?'예약 내용':panel==='faq'?'답변의 근거':'이 데모는 어떻게 작동하나요?'}</DialogTitle><Button variant="ghost" size="icon" aria-label="닫기" onClick={()=>setPanel(null)}><X/></Button></div><DialogDescription>{panel==='units'?'한 대화에서 여러 유닛을 조합합니다.':panel==='history'?'이전 말을 유지하고 바뀐 조건을 반영합니다.':panel==='photo'?'Spotlog에서 사용하는 출처 확인 사진입니다.':panel==='booking'||panel==='faq'?'실제 숙소 정보가 아닌 체험용 자료입니다.':'화면 구성과 실제 AI 연결 상태를 확인하세요.'}</DialogDescription></DialogHeader><div className="sheet-body">
 {panel==='units'&&<Composition s={s} previous={previous}/>}{panel==='history'&&<ol className="history-list">{[...session.history,s].map((item,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><div><p>{item.question}</p><small>{item.units.map(u=>u.title).join(' · ')}</small></div></li>)}</ol>}
 {panel==='photo'&&<div className="sheet-prose"><img className="credit-photo" src="/images/osulloc-museum.jpg" alt="오설록 티뮤지엄 전경"/><strong>오설록 티뮤지엄 · 과거 건물 전경</strong><p>골뱅이 (IM Seongbin) · Wikimedia Commons</p><a href="https://commons.wikimedia.org/wiki/File:O%27Sulloc_Tea_Museum,_Jeju_(%EC%98%A4%EC%84%A4%EB%A1%9D_%EB%85%B9%EC%B0%A8%EB%B0%95%EB%AC%BC%EA%B4%80,_%EC%A0%9C%EC%A3%BC)_-_panoramio.jpg" target="_blank" rel="noreferrer">원본 사진</a><a href="https://creativecommons.org/licenses/by-sa/3.0" target="_blank" rel="noreferrer">CC BY-SA 3.0</a><p>파일 편집 없음. 화면 비율에 따라 잘려 보일 수 있습니다. 과거 사진이며 현재 시설 모습과 다를 수 있어요.</p></div>}
 {panel==='booking'&&<div className="sheet-prose"><strong>모아 스테이 · DEMO–2048</strong><p>스탠다드룸 · 2인 · 1박</p><p>체크인 15:00 / 체크아웃 11:00</p><p>예약 유닛을 보여주기 위한 가상 예시입니다.</p><Button className="unit-action" onClick={()=>action('체크인 전에 짐 보관 규정 보여줘')}>짐 보관 안내 보기<ChevronRight/></Button></div>}
 {panel==='faq'&&<div className="sheet-prose"><span className="category faq">체험용 FAQ</span><h3>{faqTitle}</h3><p>{faqText}</p><p>로컬 샘플입니다. 실제 RAG 검색이나 숙소 규정을 조회한 결과가 아닙니다.</p><Button className="unit-action" onClick={()=>action('짐을 맡길 때 영어로 말할 문장 보여줘')}>직원에게 말할 문장<Languages/></Button></div>}
 {panel==='about'&&<div className="sheet-prose"><span className="category food">{s.mode==='jev'?'실제 Jev 호출 완료':'현재: 규칙 기반 체험'}</span><p>여행 상황 → 필요한 유닛 판단 → 우선순위와 표현 결정 → 하나의 화면으로 조합합니다.</p><p>식사, 시간, 이동, 예산 등 12개 유닛이 기존 조건을 이어받고 추가·제외·재배치됩니다.</p><h3>Jev의 역할</h3><p>서버 연결이 설정되면 Jev가 같은 대화를 보고 유닛별 중요도와 현재 조건을 한 번의 요청으로 판단합니다.</p><p>{s.mode==='jev'?`이번 호출: ${s.model} · ${s.elapsedMs}ms. 비교 실험 결과는 아닙니다.`:'현재 Jev 키가 설정되지 않아 실제 호출하지 않습니다. 반응 속도나 정확도 개선은 아직 검증하지 않았습니다.'}</p><a href="https://docs.typesafe.ai/api" target="_blank" rel="noreferrer">Jev 공식 API 문서<ArrowUpRight size={14}/></a><p>디자인은 Spotlog의 현재 모바일웹 기준을 적용했습니다.</p></div>}
 </div></DialogContent></Dialog></div>;
}

