const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('C:/Users/Giry/.codex/worktrees/a125/Spotlog/node_modules/@playwright/test');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/router.project-osrm.org|tile.openstreetmap.org/,r=>r.abort());
 await page.goto('http://127.0.0.1:5210/tests/trip-usability.html');await page.locator('.plan-stop').first().waitFor();
 let trip=await page.evaluate(()=>window.reviewTrip);
 await page.getByRole('button',{name:'DAY 1 메뉴',exact:true}).tap();await page.getByRole('button',{name:'이 DAY 복사',exact:true}).tap();trip=await page.evaluate(()=>window.reviewTrip);assert.equal(trip.travelProgress.dayId,trip.days[3].dayId);assert.equal(await page.locator('.plan-day h2').textContent(),'DAY 4');
 await page.reload();await page.locator('.plan-stop').first().waitFor();assert.equal(await page.locator('.plan-day h2').textContent(),'DAY 4');
 // Use a separate browser context to check App wiring and storage migration, never the user's records.
 const appContext=await browser.newContext({viewport:{width:390,height:844}});await appContext.addInitScript(value=>localStorage.setItem('spotlog.web.journeys.v4',JSON.stringify([value])),trip);
 const app=await appContext.newPage();app.on('pageerror',e=>errors.push(e.message));await app.route(/router.project-osrm.org|tile.openstreetmap.org/,r=>r.abort());await app.goto('http://127.0.0.1:5210/#trips');await app.locator('.journey-main').filter({hasText:'여행 사용 흐름 검수'}).click();await app.locator('.personal-trip').waitFor();assert.equal(await app.locator('.plan-day h2').textContent(),'DAY 4');
 await app.getByRole('button',{name:'이날의 동선 지도',exact:true}).click();await app.getByRole('button',{name:'점심 식당 · 구간 확인·수정',exact:true}).click();await app.getByRole('button',{name:'이 장소를 다른 DAY로 이동',exact:true}).click();assert.equal(await app.getByText('대상 DAY',{exact:true}).count(),1);await app.screenshot({path:`${__dirname}/app-warning-transfer-390.png`});
 // A fresh English touch fixture uses the same components; the product names remain Korean.
 const en=await browser.newContext({viewport:{width:320,height:844},isMobile:true,hasTouch:true});await en.addInitScript(()=>localStorage.setItem('spotlog.ui.language.v1','en'));const enPage=await en.newPage();enPage.on('pageerror',e=>errors.push(e.message));await enPage.goto('http://127.0.0.1:5210/tests/trip-usability.html');await enPage.getByRole('button',{name:'점심 식당 · Place menu',exact:true}).tap();assert.equal(await enPage.getByRole('button',{name:'Visited',exact:true}).count(),1);await enPage.getByRole('button',{name:'Replace just this place',exact:true}).tap();await enPage.getByRole('button',{name:'다른 점심 식당 · Choose',exact:true}).tap();assert.equal(await enPage.getByRole('button',{name:'Replace with this place',exact:true}).count(),1);assert.equal(await enPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await enPage.screenshot({path:`${__dirname}/english-touch-320.png`});
 assert.deepEqual(errors,[]);fs.writeFileSync(`${__dirname}/integration-results.json`,JSON.stringify({touchCopyResume:true,appStorage:true,appMapWarningTransfer:true,englishTouch:true,pageErrors:errors},null,2));console.log('Touch copy/resume, App warning→move, English touch passed.');await context.close();await appContext.close();await en.close();
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
