const assert = require('node:assert/strict');
const { chromium } = require('C:/Users/Giry/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base = 'http://127.0.0.1:5197/';
const repoKey = 'spotlog.local.repository.v2';
const savedKey = 'spotlog.web.saved.v3';
const journeyKey = 'spotlog.web.journeys.v4';
const place = { id: 'jeju-hyeopjae', kind: 'LANDMARK', name: '협재해수욕장', area: '제주 한림', address: '제주', lat: 33.3938, lng: 126.2397, image: '', description: '기존 장소', note: '기존 메모 보존', duration: '1시간' };
const legacy = { id: 'qa-legacy-trip', title: '기존 내 여행 보존 검사', region: '제주', dateRange: '날짜 미정', duration: '1박 2일', status: 'PLANNING', visibility: 'PRIVATE', cover: '', summary: '보존', story: '기존 이야기', tags: [], saves: 0, author: '검수', isMine: true, days: [1,2].map(day => ({ day, date: `DAY ${day}`, title: '기존 날짜', story: '기존 글', places: day === 2 ? [place] : [], blocks: day === 2 ? [{ id: 'legacy-text', type: 'TEXT', body: '삭제하면 안 되는 기존 글' }, { id: 'legacy-place', type: 'PLACE', placeId: place.id }] : [] })) };
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page = await context.newPage(); const errors=[];
  page.on('pageerror', error => errors.push(error.message));
  await context.addInitScript(({savedKey, journeyKey, legacy}) => { if (!localStorage.getItem('qa-fixture-ready')) { localStorage.setItem(savedKey, JSON.stringify(['jeju-hyeopjae'])); localStorage.setItem(journeyKey, JSON.stringify([legacy])); localStorage.setItem('qa-fixture-ready','1'); } }, {savedKey,journeyKey,legacy});
  await page.goto(base+'#saved');
  await page.getByRole('heading',{name:'저장한 장소',exact:true}).waitFor();
  assert.equal(await page.getByText('기존 내 여행 보존 검사 · DAY 2',{exact:false}).count() > 0,true);
  const backup=await page.evaluate(()=>JSON.parse(localStorage.getItem('spotlog.local.before-migration.v2')));
  assert.deepEqual(JSON.parse(backup.records[journeyKey]),[legacy]);
  assert.deepEqual(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),journeyKey),[legacy]);
  // Change only saved records; legacy journey remains intact after reload.
  await page.getByRole('button',{name:'장소',exact:true}).click();
  await page.getByRole('button',{name:'지역 안내',exact:true}).click();
  const input=page.getByRole('textbox',{name:'랜드마크 지역 검색'});
  await input.fill('협재');
  await page.getByRole('button',{name:'저장됨',exact:true}).click();
  await page.reload();
  const records=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).records,repoKey);
  assert.deepEqual(JSON.parse(records[savedKey]),[]);
  assert.deepEqual(JSON.parse(records[journeyKey]),[legacy]);
  // Search/list position remains when returning from a journal.
  await page.getByRole('button',{name:'여행기',exact:true}).click();
  await page.getByRole('textbox',{name:'여행기 지역 검색'}).fill('서울');
  await page.getByRole('button',{name:'당일치기',exact:true}).click();
  await page.getByRole('button',{name:'여행기 먼저 보기',exact:false}).first().click();
  const returnTop=await page.evaluate(()=>history.state.scrollTop);
  await page.getByRole('button',{name:'목록으로 돌아가기',exact:true}).click();
  await page.getByRole('textbox',{name:'여행기 지역 검색'}).waitFor();
  assert.equal(await page.getByRole('textbox',{name:'여행기 지역 검색'}).inputValue(),'서울');
  const actualTop=await page.locator('.content').evaluate(el=>el.scrollTop);
  const expectedTop=await page.evaluate(()=>history.state.scrollTop);
  assert.ok(Math.abs(actualTop-expectedTop)<3, `scroll restore ${actualTop}/${expectedTop}, detail ${returnTop}`);
  // Corrupt migration source must be retained, visible and non-writable.
  const corruptContext=await browser.newContext({viewport:{width:390,height:844}});
  await corruptContext.addInitScript(key=>localStorage.setItem(key,'{broken-source'),journeyKey);
  const corrupt=await corruptContext.newPage();
  await corrupt.goto(base+'#places-guide');
  await corrupt.getByRole('alert').waitFor();
  await corrupt.getByRole('textbox',{name:'랜드마크 지역 검색'}).fill('협재');
  await corrupt.getByRole('button',{name:'이 장소 저장',exact:true}).click();
  assert.equal(await corrupt.evaluate(key=>localStorage.getItem(key),journeyKey),'{broken-source');
  assert.equal(await corrupt.evaluate(key=>localStorage.getItem(key),repoKey),null);
  assert.equal(await corrupt.getByRole('button',{name:'저장됨',exact:true}).count(),0);
  await corrupt.screenshot({path:'artifacts/phase1-storage-protection.png'});
  // Existing creation/editor sheets share the same accessible back handling.
  await page.getByRole('button',{name:'내 여행',exact:true}).click();
  await page.getByRole('button',{name:'새 여행',exact:true}).click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('textbox',{name:'여행 제목',exact:true}).fill('키보드와 뒤로가기 검수');
  await page.getByRole('button',{name:'여행 만들기',exact:true}).click();
  await page.getByRole('textbox',{name:'여행기 제목',exact:true}).waitFor();
  await page.getByRole('button',{name:'작성 화면 뒤로가기',exact:true}).click();
  await page.getByRole('heading',{name:'내 여행',exact:true}).waitFor();
  assert.equal(new URL(page.url()).hash,'#trips');
  assert.equal(await page.getByRole('dialog').count(),0);
  assert.deepEqual(errors,[]);
  console.log('PASS legacy snapshot/preservation, saved reload, community filters/back scroll, corrupt storage protection, create/editor sheet navigation, no page errors');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
